name: dart_mongo_server_rpc1
description: A sample command-line application.
version: 0.0.1
#homepage: https://www.example.com
#author: child <email@example.com>

environment:
#  sdk: '>=2.0.0-dev.49.0'

dependencies:
  rpc: ^0.5.8
  mongo_dart: ^0.3.1 
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
  build_runner: ^0.8.8 
  build_web_compilers: ^0.3.7+3
  browser: ^0.10.0+3
